apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-alpine-deployment
  labels:
    app: my-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-alpine
  template:
    metadata:
      labels:
        app: my-alpine
    spec:
      containers:
      - name: my-alpine
        image: dqminh2810/my-alpine:v1.0
        ports:
          - containerPort: 80 # Example port if your Alpine application serves content
        command: ["sh", "-c", "echo 'Hello from Alpine!' && sleep infinity"] # Example command to keep the container running
      imagePullSecrets:
      - name: docker-reg-creds