apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        livenessProbe: # Liveness probe to restart unhealthy containers
          httpGet:
            path: / # Path to check for liveness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe: # Readiness probe to ensure container is ready to serve traffic
          httpGet:
            path: / # Path to check for readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
         
          